### ISSUE TITLE
Minimum Target Version

### ISSUE THREAD

**Issue by queequac** [onovotny/Zeroconf#100]
I wanted to upgrade to version 3.0, but the minimum version for the package was set higher... unfortunately I am still supporting several Windows 10 Mobile users, lots of them dealing with older Windows 10 versions.

Is there any specific reason for the new minimum version? The only real change beneath bug fixes was Rx4, and that one should be able to run down to build uwp 10240. Do I have to upgrade my minimum supported version just for Zeroconf now? (I know, old version are not supported anymore, but I was the good samaritan so far also caring for the minorities still using old Windows versions, even having several switches to handle features not available in older windows version.😋)

**Comment by onovotny** [comment]
There was also a fix involving the network stack, and I decided not to try to do the fix for both network implementations. That's primarily why it was dropped.

After October 9th, 16299 is the lowest version of Win10 that Microsoft will support, so if it's not now, it's in four months. 2.9 is still around and Rx3 works with Rx4 apps that use the compatibility package.

**Comment by queequac** [comment]
Not completly true, 1709 is the lowest version in 4 months, but on Mobile this is not API version 16299 but 15254... support lasting until end of 2019.

I have still significant users on old versions, so I won't increase the minimum version in the near future... not sure if I really stick to 2.9 then or handcraft myself some 3.0.

**Comment by queequac** [comment]
Unlikely minimum version will change (to lower). So okay to close this one. ;)
