### ISSUE TITLE
Try to discover service in openhab multicast functionality failed

### ISSUE THREAD

**Issue by rsattler** [onovotny/Zeroconf#5]
Hello,

i try to discover the openhabe service with zeroconf on a windows phone 8.1. But the ResolvAsync gives me no data. 
There is an multicast DNS/Bonjour functionality to openHAB. Which announced as

HTTP is announced as _openhab-server._tcp.local. and it's name is openHAB
HTTPS is announced as _openhab-server-ssl._tcp.local. and it's name is openHAB-ssl

Service discovery will return several parameters of openHAB:

IP address (like 192.168.1.20)
TCP port (like 8080)
uri attribute (like /rest)
The base URL for openHAB will look like this: http://192.168.1.20:8080/rest

I try your example code in a little test app with my windows phone 8.1. With the following code

        private async void Button_Click(object sender, RoutedEventArgs e)
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("OpenHab data:\n");

            IReadOnlyList<IZeroconfHost> results = await ZeroconfResolver.ResolveAsync("_openhab-server._tcp.local.");

            foreach (var item in results)
            {
                sb.Append(item.DisplayName + "\n");
                sb.Append(item.Id + "\n");
                sb.Append(item.IPAddress + "\n");
                sb.Append(item.Services + "\n");
            }

            txBlock.Text = sb.ToString();
        }

But the results is everytime empty. Any idea whats wrong? My phone is connected to my local lan.

**Comment by onovotny** [comment]
@rsattler Been very busy lately. I'm not familiar with openHAB, how can I install/repro this issue? Looking at their [downloads](http://www.openhab.org/downloads.html) page, there's a lot of options; what's the minimum I need?

I'm really not sure what's going on yet as to the best of my knowledge, I'm following the RFC's [1](http://tools.ietf.org/html/rfc6762)[2](http://tools.ietf.org/html/rfc6763), but there could still be gaps.

**Comment by rsattler** [comment]
You must download the runtime core and demo setup. Then you must copy the demo setup (=demo config) into the runtime and then start the server via start.bat. Less than 2 min. to do for all. With the start.bat the service will start automatic.

**Comment by kobush** [comment]
Hi Oren,
I'm working with Rene on the openHAB Windows Phone client. I've looked more closely into this issue and found that I get the correct response when I change this line in NetworkInterface.BindToSocketAndWriteQuery from
```C#
await socket.BindServiceNameAsync("", NetworkInformation.GetInternetConnectionProfile().NetworkAdapter)
```
to (same as you had for Windows Phone):
```C#
await socket.BindServiceNameAsync("5353")
```
This returned me correct record from openHAB server. However the ZeroconfHost record didn't include all information. Here are all the answers returned:

![openhab](https://cloud.githubusercontent.com/assets/513062/5872623/da040d02-a2ed-11e4-8e89-653a77eb71ab.png)

What does it tell me? There are two instances for protocol "_openhab-server._tcp.local." found:
 1. "openHAB (2)._openhab-server._tcp.local."
   * Text information  "uri=/services/habmin"
   * Uses service "SERVER.local." on port 8080
 2. "openHAB._openhab-server._tcp.local."
   * Text information "uri=/rest"
   * Uses service "SERVER.local." on port 8080

So I should get two Services with appropriate properties. But ZeroconfHost  has none and returns only name openHAB (2)

![openhab2](https://cloud.githubusercontent.com/assets/513062/5872687/8bdd0b8c-a2ee-11e4-85f0-727a173282a7.png)

Hope this helps.

Best,
-Szymon

**Comment by kobush** [comment]
So for a quick fix in our scenario changing ResponseToZeroconf to search for records in response.Answers instead of response.Additionals makes it work correctly. 

I'm not familiar with the spec but perhaps it should search on both. Do you think this would be correct?

**Comment by onovotny** [comment]
I think that should be ok, if you can send me a PR with the changes, I can review and validate them.

I've just been super slammed lately, so I haven't had time to look into it myself.
________________________________

**Comment by queequac** [comment]
I had a similar issue. After some device's firmware update, Zeroconf could suddenly no longer find it on Windows Phone 8.1.
I did not incorporate the whole fix, but I removed the #ifdef section in the NetworkInterface.cs which

```csharp
// #if !WINDOWS_PHONE
//             //await socket.BindServiceNameAsync("", NetworkInformation.GetInternetConnectionProfile().NetworkAdapter)
//             await socket.BindServiceNameAsync("5353")
// #else
           await socket.BindServiceNameAsync("5353")
// #endif
```

What was the reason for handling that different at all?

Could you please merge at least this file and update the Nuget package?
I do not really like the idea of having a custom build version in my project now. ;-)

Cheers,
   Roland

@kobush Thanks for the fix!

**Comment by onovotny** [comment]
I'll get these merged in today. The reason for that alternate network call was for this issue:
http://blogs.msdn.com/b/wsdevsol/archive/2013/12/19/datagramsocket-multicast-functionality-on-windows-8-1-throws-an-error-0x80072af9-wsahost-not-found.aspx

Before reverting this, as it did solve another person's issue, can you try specifying the port, 5353 and see if that also solves it for you?

So please try
```csharp
await socket.BindServiceNameAsync("5353", NetworkInformation.GetInternetConnectionProfile().NetworkAdapter)
```
and let me know if that also fixes it for you.

**Comment by onovotny** [comment]
Can you please try the following branch? https://github.com/onovotny/zeroconf/tree/pr/7

If I try to explicitly bind to the local port 5353, it fails with the following exception:
```
{"Only one usage of each socket address (protocol/network address/port) is normally permitted.\r\n\r\nOnly one usage of each socket address (protocol/network address/port) is normally permitted.\r\n"}
 ```
Most likely because there is already a Bonjour service running on the machine. If you install iTunes or Xamarin, it'll install a system-wide mDNS responder, which would listen on UDP port 5353.

I don't believe this code needs to bind to the local port as it's only sending requests, not acting as a server. The pr/7 branch does have a small change to get the A records from the Answers instead of Additionals if that helps OpenHAB. Please try it and let me know if that resolves the issue with that service.

**Comment by queequac** [comment]
@onovotny At least in my case it really works only with specified port... I can see mDNS responses with wireshark, but Zeroconf does not return any service.

Why don't you bind against that port, having a try-catch arround for falling back to the approach without the specified port?

**Comment by onovotny** [comment]
@queequac Can you try the latest now? I did put that logic in there.... If you can't build from source (it now requires vs 2015 for a c# 6 syntax), I put a compiled version of the library for WinStore apps here:
https://onedrive.live.com/redir?resid=B98D981155DF4D47!627868&authkey=!AO-KPY8ddX7MmNE&ithint=file%2czip

**Comment by queequac** [comment]
@onovotny This version works for me, thanks! :)

Maybe you consider removing the whole #if !WINDOWS_PHONE section, since I do not see any real disadvantage if the phone would follow the same fallback strategy. And on WinRT the portable class will not consider the phone's branch anyhow.

**Comment by onovotny** [comment]
The WP version is needed because it still uses the API that specifies the network adapter to use to workaround a different issue (the one mentioned in the link earlier in this thread). Unfortunately that API is desktop only and throws on the phone, so I can't use that API there.

Glad to hear this is working for you now. I'll get this pushed to NuGet in the next day or two.

Can you please try one other thing though -- do you have the Bonjour mDNS responder service running on your box? It may be installed with either iTunes or Xamarin - you can check from your Services control panel.

Just wondering if everything still works or if it's able to bind to local port 5353 if that service is running and if the services you're looking for are still successfully discovered?

Thanks

**Comment by onovotny** [comment]
This is now fixed in 2.3.1, just published to NuGet

**Comment by queequac** [comment]
@onovotny Are you sure you published the fix correctly? I did extensive tests, and the official nuget package 2.3.1 does not give me any mDNS responses for my device, while your custom build (the one you provided above for download) gives me always the responses as expected.

The fix is also not yet merged into the master branch.

**Comment by onovotny** [comment]
@queequac Ack, sorry, you're right, should be fixed now: https://www.nuget.org/packages/Zeroconf/2.3.2
